plugins {
  id 'application'
  id 'java'
  id 'maven-publish'
}


apply plugin : "java"
application {
//   applicationDefaultJvmArgs = ["-Djava.library.path=/usr/local/share/zbar/lib"]
   mainClass = "com.cooplogic.app.VideoYolo"
}
group 'com.cooplogic'
version '1.0-YOLOv8'



compileJava {
   doFirst {
     
   }
}

repositories {
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes 'Main-Class': 'com.cooplogic.app.VideoYolo'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

dependencies {
    // https://mvnrepository.com/artifact/org.openpnp/opencv
    implementation group: 'org.openpnp', name: 'opencv', version: '4.9.0-0'
    // implementation group: 'org.opencv', name: 'opencv', version: '4.11.0'
    // https://mvnrepository.com/artifact/org.bytedeco/opencv
    //implementation group: 'org.bytedeco', name: 'opencv', version: '4.10.0-1.5.11'
    // https://mvnrepository.com/artifact/org.bytedeco/opencv-platform
    //implementation group: 'org.bytedeco', name: 'opencv-platform', version: '4.10.0-1.5.11'    
    //implementation group: 'org.openpnp', name: 'opencv', version: '4.6.0-0'
    //implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.11'
    //implementation group: 'org.bytedeco', name: 'opencv-platform', version: '4.10.0-1.5.11'
    //implementation group: 'org.bytedeco', name: 'ffmpeg-platform', version: '7.1-1.5.11'
    //implementation 'org.json:json:20220924'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //implementation 'org.jetbrains:annotations:22.0.0'
    //implementation 'ch.qos.logback:logback-core:+'
    //implementation 'ch.qos.logback:logback-classic:+'
    //implementation 'com.github.weliem.blessed-bluez:blessed:0.61'
    implementation 'com.github.jnr:jnr-ffi:2.2.12'
    implementation 'com.github.jnr:jnr-posix:3.1.16'
    implementation 'com.github.jnr:jnr-constants:0.10.4'
    implementation 'com.github.jnr:jnr-a64asm:1.0.0'
    implementation 'com.github.jnr:jnr-x86asm:1.0.0'
}



publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
